### ISSUE TITLE
/lib/Silverpop/Util/ArrayToXml.php Rename

### ISSUE THREAD

**Issue by th3fallen** [simpleweb/SilverpopPHP#11]
For the people that load this repo via Composer your ArrayToXML class name does not match the filename which can cause issues in some os' when autloading please rename this file to ArrayToXML.php

**Comment by rvarbanov** [comment]
The ArrayToXml.php file is still in the repo. When you download the zipped repo and try to unzip it 7zip tries to overwrite ArrayToXML.php with ArrayToXml.php.

The extra file should be removed from the repo.
