### ISSUE TITLE
Login Error: BLOCKED

### ISSUE THREAD

**Issue by rvarbanov** [simpleweb/SilverpopPHP#23]
Login Error: Unable to login user: silverpop@sitename.com - BLOCKED. Attempt made from IP address: xxx.xxx.xxx.xxx

I get that when I try to use the library.

Please help.

**Comment by hiddenpearls** [comment]
@rvarbanov Were you able to find the solution to this problem? 
I am facing the same issue :(

**Comment by tholder** [comment]
looks simply like they are blocking your IP. You should speak to silverpop.

**Comment by hiddenpearls** [comment]
@tholder hmm.

**Comment by hiddenpearls** [comment]
@tholder What is the best way to use it with OAuth credentials?
